# Generated by Django 2.1.2 on 2018-12-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('direccion', models.CharField(max_length=140)),
                ('ciudad', models.CharField(max_length=140)),
                ('comuna', models.CharField(max_length=140)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=140)),
            ],
        ),
    ]
