# Generated by Django 2.1.2 on 2018-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Nombre', models.CharField(max_length=10)),
                ('RutCliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NombreMascota', models.CharField(max_length=10)),
                ('Raza', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Fotografia', models.ImageField(upload_to='media')),
                ('Estado', models.CharField(choices=[('1', 'Rescatado'), ('2', 'Disponible'), ('3', 'Adoptado')], default=1, max_length=10)),
            ],
        ),
    ]
